#!/bin/bash
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 4 -*-
#
# Copyright (C) 2015 Canonical, Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR=$1
if [[ $DIR != /* ]]; then
    echo "Please specify a target directory as the first argument"
    exit 1
fi
shift

set -o pipefail
set +e
dpkg -L $* | grep '^/' | while read file; do
    mkdir -p "$DIR$(dirname \"$file\")"
    if [ -h "$file" ] && [ "$(readlink \"$file\")" != "." ]; then
        # Disallow a self-redirection like /usr/bin/X11 because then the snap
        # size explodes as we do recursive copies.  Let's just accept that
        # /usr/bin/X11 won't work.
        cp -prL "$file" "$DIR$file"
    elif [ -d "$file" ]; then
        mkdir -p "$DIR$file"
    else
        cp -p "$file" "$DIR$file"
    fi
done
